@startuml class

class Users {
    {static} Auto_increment id
    {static} String name
    {static} String email
    {static} String password
    {static} Boolean token
    {static} Boolean is_registered
    {static} Boolean is_admin
    {static} Datetime created_at
    {static} Datetime updated_at
    {static} Boolean is_deleted
    ---
    getAllUsers()
    findUserById()
    findUserByName()
    findUserByNameOrMail()
    findUserByNameAndToken()
    createNewUser()
    activateUser()
    deleteUser()
    authentificationFailed()
    loggedOnly()
    adminOnly()
}

class Posts {
    {static} Auto_increment id
    {static} String user_id
    {static} String name
    {static} String picture
    {static} String catchphrase
    {static} Text content
    {static} Datetime created_at
    {static} Datetime updated_at
    {static} Boolean is_deleted
    ---
    getAllPosts()
    getLastPosts()
    getPostById()
    createNewPost()
    updatePost()
    addPicture()
    deletePost()
}

class Comments {
    {static} Auto_increment id
    {static} String post_id
    {static} String user_id
    {static} String content
    {static} Boolean is_confirmed
    {static} Datetime created_at
    {static} Datetime updated_at
    {static} Boolean is_deleted
    ---
    getAllCommentsWithUsernames()
    getCommentsByPostsWithUsernames()
    getCommentById()
    getNumberOfNotConfirmedComments()
    createComment()
    confirmAllComments()
    deleteComment()
}

Users "1" - "many" Posts : writes
Users "1" - "many" Comments : post
Posts "1" -- "many" Comments : contains

@enduml