@startuml valider ou supprimer un commentaire

actor Administrateur
boundary Systeme
database BDD

Administrateur -> Systeme: login() : doit se connecter
Systeme -> BDD: recherche des commentaires
BDD --> Systeme : commentaires trouvés
Systeme --> Administrateur: dashboard() / getAllCommentsWithUsernames() : Affichage du Dashboard

alt validation des commentaires
    Administrateur -> Systeme: confirmAllComments() : valide tout les commentaires en attente
    Systeme -> BDD: passage de tout les commentaires -> is_validate
    BDD --> Systeme : commentaires validés
    Systeme --> Administrateur: notification d'approbation des commentaires + Affichage du Dashboard
else Suppression d'un commentaire
    Administrateur -> Systeme: deleteComment() : supprime un commentaire
    Systeme -> BDD: passage de is_deleted à true
    BDD --> Systeme : commentaire supprimé
    Systeme --> Administrateur: notification de la suppression du commentaire +  Affichage du Dashboard
end

@enduml