@startuml poster un commentaire

actor utilisateur
boundary Systeme
database BDD

utilisateur -> Systeme: post() : afficher un article
note left: l'utilisateur est \n un visiteur \n authentifié
Systeme -> BDD: recherche de l'article
BDD --> Systeme : article trouvé
Systeme --> utilisateur: Affichage de l'article

utilisateur -> Systeme: createComment() : envoi des données
Systeme -> BDD: enregistrement du message (pas encore validé)
BDD --> Systeme : message enregistré
Systeme --> utilisateur: Notification de création réussie (en attente de validation)

@enduml